=== CosimoLombo02/TheWasteLandForum/Code/XML/DTD/conseguenzeSegnalazioniDTD.dtd
<!ELEMENT ConseguenzeSegnalazioni (ConseguenzaSegnalazioni*)>
<!ELEMENT ConseguenzaSegnalazioni (codiceSegnalazione+, testoWarning*, versoChi+, descrizioneConseguenza+, dataEvasioneSegnalazione+, utenteGestore+)>
<!ELEMENT codiceSegnalazione (#PCDATA)>
<!ELEMENT testoWarning (#PCDATA)>
<!ELEMENT versoChi (#PCDATA)>
<!ELEMENT descrizioneConseguenza (#PCDATA)>
<!ELEMENT dataEvasioneSegnalazione (#PCDATA)>
<!ELEMENT utenteGestore (#PCDATA)>

=== CosimoLombo02/TheWasteLandForum/Code/XML/conseguenzeSegnalazioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ConseguenzeSegnalazioni SYSTEM "../XML/DTD/conseguenzeSegnalazioniDTD.dtd">
<ConseguenzeSegnalazioni><ConseguenzaSegnalazioni><codiceSegnalazione>1</codiceSegnalazione><testoWarning>ale&#13;
ale&#13;
ale</testoWarning><versoChi>account2</versoChi><descrizioneConseguenza>2</descrizioneConseguenza><dataEvasioneSegnalazione>2024-12-04</dataEvasioneSegnalazione><utenteGestore>admin</utenteGestore></ConseguenzaSegnalazioni></ConseguenzeSegnalazioni>
